# Generated by Django 4.2.21 on 2025-09-04 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailAutomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('title', models.CharField(max_length=256, unique=True)),
                ('method_title', models.CharField(editable=False, max_length=100)),
                ('model', models.CharField(choices=[('helpdesk.models.Comment', 'Comment'), ('project.models.Project', 'Project'), ('recruitment.models.CandidateDocument', 'CandidateDocument'), ('base.models.ShiftRequest', 'ShiftRequest'), ('onboarding.models.CandidateTask', 'CandidateTask'), ('onboarding.models.OnboardingStage', 'OnboardingStage'), ('asset.models.Asset', 'Asset'), ('django.contrib.auth.models.User', 'User'), ('recruitment.models.SkillZoneCandidate', 'SkillZoneCandidate'), ('leave.models.LeaveallocationrequestComment', 'LeaveallocationrequestComment'), ('attendance.models.AttendanceActivity', 'AttendanceActivity'), ('base.models.WorkTypeRequestComment', 'WorkTypeRequestComment'), ('recruitment.models.InterviewSchedule', 'InterviewSchedule'), ('base.models.WorkTypeRequest', 'WorkTypeRequest'), ('horilla_documents.models.Document', 'Document'), ('employee.models.EmployeeNote', 'EmployeeNote'), ('leave.models.LeaveRequest', 'LeaveRequest'), ('onboarding.models.OnboardingTask', 'OnboardingTask'), ('asset.models.AssetAssignment', 'AssetAssignment'), ('project.models.Task', 'Task'), ('recruitment.models.StageNote', 'StageNote'), ('accessibility.models.DefaultAccessibility', 'DefaultAccessibility'), ('attendance.models.Attendance', 'Attendance'), ('payroll.models.models.Contract', 'Contract'), ('recruitment.models.HistoricalCandidate', 'HistoricalCandidate'), ('base.models.ShiftRequestComment', 'ShiftRequestComment'), ('offboarding.models.OffboardingEmployee', 'OffboardingEmployee'), ('recruitment.models.RecruitmentSurveyAnswer', 'RecruitmentSurveyAnswer'), ('pms.models.Meetings', 'Meetings'), ('base.models.RotatingShiftAssign', 'RotatingShiftAssign'), ('base.models.RotatingWorkType', 'RotatingWorkType'), ('attendance.models.AttendanceOverTime', 'AttendanceOverTime'), ('offboarding.models.Offboarding', 'Offboarding'), ('pms.models.KeyResultFeedback', 'KeyResultFeedback'), ('pms.models.MeetingsAnswer', 'MeetingsAnswer'), ('auditlog.models.LogEntry', 'LogEntry'), ('project.models.TimeSheet', 'TimeSheet'), ('pms.models.Answer', 'Answer'), ('attendance.models.AttendanceRequestComment', 'AttendanceRequestComment'), ('pms.models.Comment', 'Comment'), ('payroll.models.models.Reimbursement', 'Reimbursement'), ('payroll.models.models.LoanAccount', 'LoanAccount'), ('onboarding.models.CandidateStage', 'CandidateStage'), ('recruitment.models.CandidateRating', 'CandidateRating'), ('horilla_automations.models.MailAutomation', 'MailAutomation'), ('recruitment.models.CandidateDocumentRequest', 'CandidateDocumentRequest'), ('offboarding.models.ResignationLetter', 'ResignationLetter'), ('leave.models.CompensatoryLeaveRequest', 'CompensatoryLeaveRequest'), ('payroll.models.models.Deduction', 'Deduction'), ('attendance.models.AttendanceLateComeEarlyOut', 'AttendanceLateComeEarlyOut'), ('payroll.models.models.Payslip', 'Payslip'), ('employee.models.Employee', 'Employee'), ('pms.models.EmployeeBonusPoint', 'EmployeeBonusPoint'), ('facedetection.models.EmployeeFaceDetection', 'EmployeeFaceDetection'), ('recruitment.models.RejectedCandidate', 'RejectedCandidate'), ('pms.models.EmployeeObjective', 'EmployeeObjective'), ('pms.models.Feedback', 'Feedback'), ('leave.models.LeaverequestComment', 'LeaverequestComment'), ('leave.models.CompensatoryLeaverequestComment', 'CompensatoryLeaverequestComment'), ('helpdesk.models.Ticket', 'Ticket'), ('pms.models.EmployeeKeyResult', 'Employee Key Results'), ('payroll.models.models.Allowance', 'Allowance'), ('horilla_documents.models.DocumentRequest', 'DocumentRequest'), ('pms.models.Objective', 'Objective'), ('base.models.AnnouncementComment', 'AnnouncementComment'), ('attendance.models.WorkRecords', 'WorkRecords'), ('leave.models.LeaveAllocationRequest', 'LeaveAllocationRequest'), ('employee.models.EmployeeWorkInformation', 'EmployeeWorkInformation'), ('base.models.RotatingWorkTypeAssign', 'RotatingWorkTypeAssign'), ('payroll.models.models.WorkRecord', 'WorkRecord'), ('pms.models.AnonymousFeedback', 'AnonymousFeedback'), ('base.models.NotificationSound', 'NotificationSound'), ('employee.models.DisciplinaryAction', 'DisciplinaryAction'), ('base.models.RotatingShift', 'RotatingShift'), ('payroll.models.models.ReimbursementrequestComment', 'ReimbursementrequestComment'), ('employee.models.Policy', 'Policy'), ('helpdesk.models.DepartmentManager', 'DepartmentManager'), ('offboarding.models.OffboardingStage', 'OffboardingStage'), ('recruitment.models.Candidate', 'Candidate'), ('biometric.models.BiometricEmployees', 'BiometricEmployees'), ('base.models.DashboardEmployeeCharts', 'DashboardEmployeeCharts'), ('employee.models.BonusPoint', 'BonusPoint'), ('helpdesk.models.ClaimRequest', 'ClaimRequest'), ('recruitment.models.Stage', 'Stage'), ('leave.models.AvailableLeave', 'AvailableLeave'), ('recruitment.models.Recruitment', 'Recruitment'), ('base.models.PenaltyAccounts', 'PenaltyAccounts'), ('offboarding.models.OffboardingTask', 'OffboardingTask'), ('base.models.Announcement', 'Announcement'), ('employee.models.EmployeeBankDetails', 'EmployeeBankDetails'), ('asset.models.AssetRequest', 'AssetRequest'), ('leave.models.LeaveRequestConditionApproval', 'LeaveRequestConditionApproval'), ('onboarding.models.OnboardingPortal', 'OnboardingPortal'), ('offboarding.models.OffboardingNote', 'OffboardingNote')], max_length=100)),
                ('mail_to', models.TextField(verbose_name='Mail to/Notify to')),
                ('mail_details', models.CharField(help_text='Fill mail template details(reciever/instance, `self` will be the person who trigger the automation), `As template` option will sent instead of the mail template', max_length=250)),
                ('mail_detail_choice', models.TextField(default='', editable=False)),
                ('trigger', models.CharField(choices=[('on_create', 'On Create'), ('on_update', 'On Update'), ('on_delete', 'On Delete')], max_length=10)),
                ('delivery_channel', models.CharField(choices=[('email', 'Send as Email'), ('notification', 'Send as Notification'), ('both', 'Send as Email and Notification')], default='email', max_length=50, verbose_name='Choose Delivery Channel')),
                ('condition_html', models.TextField(editable=False, null=True)),
                ('condition_querystring', models.TextField(editable=False, null=True)),
                ('condition', models.TextField()),
                ('also_sent_to', models.ManyToManyField(blank=True, to='employee.employee', verbose_name='Also Send to')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('mail_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.horillamailtemplate')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('template_attachments', models.ManyToManyField(blank=True, related_name='template_attachment', to='base.horillamailtemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
