# Generated by Django 4.2.21 on 2025-11-09 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_add_philippines_payroll_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employee',
            name='employee_ph_region_idx',
        ),
    ]
