# Generated by Django 4.2.21 on 2025-10-24 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_initial'),
        ('employee', '0001_initial'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='SSSContributionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('effective_date', models.DateField(help_text='Date when this table becomes effective', verbose_name='Effective Date')),
                ('min_compensation', models.DecimalField(decimal_places=2, help_text='Minimum monthly salary credit range', max_digits=10, verbose_name='Minimum Compensation')),
                ('max_compensation', models.DecimalField(decimal_places=2, help_text='Maximum monthly salary credit range', max_digits=10, verbose_name='Maximum Compensation')),
                ('monthly_salary_credit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monthly Salary Credit (MSC)')),
                ('employee_contribution', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Employee Contribution')),
                ('employer_contribution', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Employer Contribution')),
                ('total_contribution', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Contribution')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'SSS Contribution Table',
                'verbose_name_plural': 'SSS Contribution Tables',
                'ordering': ['effective_date', 'min_compensation'],
            },
        ),
        migrations.CreateModel(
            name='PhilippineTaxBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('year', models.IntegerField(help_text='Year when this tax table is applicable', verbose_name='Tax Year')),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('semi_monthly', 'Semi-Monthly'), ('annual', 'Annual')], default='monthly', max_length=15, verbose_name='Period')),
                ('min_income', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Minimum Taxable Income')),
                ('max_income', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank for unlimited', max_digits=15, null=True, verbose_name='Maximum Taxable Income')),
                ('base_tax', models.DecimalField(decimal_places=2, default=0, help_text='Fixed tax amount for this bracket', max_digits=15, verbose_name='Base Tax')),
                ('excess_rate', models.DecimalField(decimal_places=2, default=0, help_text='Tax rate applied to income exceeding minimum', max_digits=5, verbose_name='Tax Rate on Excess (%)')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Philippine Tax Bracket',
                'verbose_name_plural': 'Philippine Tax Brackets',
                'ordering': ['year', 'period', 'min_income'],
            },
        ),
        migrations.CreateModel(
            name='PhilippineLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('loan_type', models.CharField(choices=[('sss_salary', 'SSS Salary Loan'), ('sss_calamity', 'SSS Calamity Loan'), ('pagibig_housing', 'Pag-IBIG Housing Loan'), ('pagibig_multi', 'Pag-IBIG Multi-Purpose Loan')], max_length=20, verbose_name='Loan Type')),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Loan Amount')),
                ('monthly_amortization', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monthly Amortization')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Outstanding Balance')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ph_loans', to='employee.employee', verbose_name='Employee')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Philippine Loan',
                'verbose_name_plural': 'Philippine Loans',
            },
        ),
        migrations.CreateModel(
            name='PhilippineEmployeeTaxInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('sss_number', models.CharField(blank=True, help_text='Social Security System number', max_length=20, null=True, verbose_name='SSS Number')),
                ('philhealth_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='PhilHealth Number')),
                ('pagibig_number', models.CharField(blank=True, help_text='HDMF Member ID', max_length=20, null=True, verbose_name='Pag-IBIG Number')),
                ('tin', models.CharField(blank=True, help_text='Tax Identification Number', max_length=15, null=True, verbose_name='TIN')),
                ('rdo_code', models.CharField(blank=True, help_text='Revenue District Office code', max_length=10, null=True, verbose_name='RDO Code')),
                ('bir_filing_status', models.CharField(choices=[('S', 'Single'), ('ME', 'Married Employee'), ('ME1', 'Married Employee with 1 dependent'), ('ME2', 'Married Employee with 2 dependents'), ('ME3', 'Married Employee with 3 dependents'), ('ME4', 'Married Employee with 4 dependents')], default='S', max_length=3, verbose_name='BIR Filing Status')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ph_tax_info', to='employee.employee', verbose_name='Employee')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Philippine Employee Tax Info',
                'verbose_name_plural': 'Philippine Employee Tax Info',
            },
        ),
        migrations.CreateModel(
            name='PhilHealthContributionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('effective_date', models.DateField(verbose_name='Effective Date')),
                ('contribution_rate', models.DecimalField(decimal_places=2, help_text='Total contribution rate (e.g., 5.00 for 5%)', max_digits=5, verbose_name='Contribution Rate (%)')),
                ('min_monthly_premium', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Minimum Monthly Premium')),
                ('max_monthly_premium', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Maximum Monthly Premium')),
                ('income_floor', models.DecimalField(decimal_places=2, default=10000, help_text='Minimum basic salary for premium calculation', max_digits=10, verbose_name='Income Floor')),
                ('income_ceiling', models.DecimalField(decimal_places=2, default=100000, help_text='Maximum basic salary for premium calculation', max_digits=10, verbose_name='Income Ceiling')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'PhilHealth Contribution Table',
                'verbose_name_plural': 'PhilHealth Contribution Tables',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='PayrollCountrySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('country', models.CharField(choices=[('PH', 'Philippines'), ('US', 'United States')], default='US', max_length=2, verbose_name='Country')),
                ('currency_code', models.CharField(default='USD', help_text='ISO 4217 currency code (e.g., PHP, USD)', max_length=3, verbose_name='Currency Code')),
                ('enable_ph_payroll', models.BooleanField(default=False, help_text='Enable Philippine statutory deductions and tax calculations', verbose_name='Enable Philippine Payroll')),
                ('company_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_country_settings', to='base.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Payroll Country Setting',
                'verbose_name_plural': 'Payroll Country Settings',
            },
        ),
        migrations.CreateModel(
            name='PagIBIGContributionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('effective_date', models.DateField(verbose_name='Effective Date')),
                ('min_compensation', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Minimum Compensation')),
                ('max_compensation', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank for unlimited', max_digits=10, null=True, verbose_name='Maximum Compensation')),
                ('employee_rate', models.DecimalField(decimal_places=2, help_text='Employee contribution rate', max_digits=5, verbose_name='Employee Rate (%)')),
                ('employer_rate', models.DecimalField(decimal_places=2, help_text='Employer contribution rate', max_digits=5, verbose_name='Employer Rate (%)')),
                ('max_employee_contribution', models.DecimalField(decimal_places=2, default=100, help_text='Maximum employee contribution amount', max_digits=10, verbose_name='Max Employee Contribution')),
                ('max_employer_contribution', models.DecimalField(decimal_places=2, default=100, help_text='Maximum employer contribution amount', max_digits=10, verbose_name='Max Employer Contribution')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Pag-IBIG Contribution Table',
                'verbose_name_plural': 'Pag-IBIG Contribution Tables',
                'ordering': ['-effective_date', 'min_compensation'],
            },
        ),
        migrations.CreateModel(
            name='DeMinimisCustomBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('benefit_name', models.CharField(max_length=100, verbose_name='Benefit Name')),
                ('annual_limit', models.DecimalField(decimal_places=2, help_text='Maximum tax-exempt amount per year', max_digits=10, verbose_name='Annual Limit')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'De Minimis Benefit',
                'verbose_name_plural': 'De Minimis Benefits',
            },
        ),
        migrations.CreateModel(
            name='ThirteenthMonthPayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('tax_exempt_threshold', models.DecimalField(decimal_places=2, default=90000, help_text='Amount of 13th month pay that is tax-exempt', max_digits=10, verbose_name='Tax Exempt Threshold')),
                ('include_allowances', models.BooleanField(default=False, help_text='Include taxable allowances in 13th month pay calculation', verbose_name='Include Allowances')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': '13th Month Pay Config',
                'verbose_name_plural': '13th Month Pay Configs',
                'unique_together': {('year', 'company_id')},
            },
        ),
    ]
