# Generated by Django 4.2.21 on 2025-10-24 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0002_alter_reimbursement_description_ssscontributiontable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhilippinesCOLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('daily_cola', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Daily COLA Amount')),
                ('monthly_cola', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monthly COLA Amount')),
                ('is_taxable', models.BooleanField(default=False, help_text='Whether COLA is subject to withholding tax', verbose_name='Is Taxable')),
                ('effective_date', models.DateField(verbose_name='Effective Date')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'COLA Configuration',
                'verbose_name_plural': 'COLA Configurations',
            },
        ),
        migrations.CreateModel(
            name='PhilippinesHolidayPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('holiday_date', models.DateField(verbose_name='Holiday Date')),
                ('holiday_name', models.CharField(max_length=100, verbose_name='Holiday Name')),
                ('holiday_type', models.CharField(choices=[('regular', 'Regular Holiday - 200%'), ('special', 'Special Non-Working Day - 130%')], max_length=20, verbose_name='Holiday Type')),
                ('pay_multiplier', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Pay Multiplier')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Holiday Pay Configuration',
                'verbose_name_plural': 'Holiday Pay Configurations',
                'unique_together': {('holiday_date', 'company_id')},
            },
        ),
        migrations.CreateModel(
            name='PhilippinesOvertimeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('overtime_type', models.CharField(choices=[('regular_day_ot', 'Regular Day Overtime - 125%'), ('rest_day_ot', 'Rest Day Overtime - 130%'), ('special_holiday_ot', 'Special Holiday Overtime - 130%'), ('special_holiday_rest_day_ot', 'Special Holiday + Rest Day OT - 150%'), ('regular_holiday_ot', 'Regular Holiday Overtime - 160%'), ('regular_holiday_rest_day_ot', 'Regular Holiday + Rest Day OT - 260%'), ('night_differential', 'Night Differential - 10%')], max_length=50, unique=True, verbose_name='Overtime Type')),
                ('multiplier', models.DecimalField(decimal_places=2, help_text='Multiplier for the hourly rate', max_digits=5, verbose_name='Pay Multiplier')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Overtime Rule',
                'verbose_name_plural': 'Overtime Rules',
            },
        ),
        migrations.CreateModel(
            name='PhilippinesPagIbigContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Minimum Salary Range')),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maximum Salary Range')),
                ('employee_rate', models.DecimalField(decimal_places=2, default=2.0, help_text='Employee contribution rate', max_digits=5, verbose_name='Employee Rate (%)')),
                ('employer_rate', models.DecimalField(decimal_places=2, default=2.0, help_text='Employer contribution rate', max_digits=5, verbose_name='Employer Rate (%)')),
                ('employee_contribution', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Employee Contribution')),
                ('employer_contribution', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Employer Contribution')),
                ('total_contribution', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Contribution')),
                ('effective_date', models.DateField(verbose_name='Effective Date')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Pag-IBIG Contribution Table',
                'verbose_name_plural': 'Pag-IBIG Contribution Tables',
                'ordering': ['min_salary'],
            },
        ),
        migrations.CreateModel(
            name='PhilippinesPhilHealthContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Minimum Salary Range')),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maximum Salary Range')),
                ('premium_rate', models.DecimalField(decimal_places=2, default=5.0, help_text='Currently 5% of basic salary', max_digits=5, verbose_name='Premium Rate (%)')),
                ('monthly_premium', models.DecimalField(decimal_places=2, help_text='Total monthly premium', max_digits=10, verbose_name='Monthly Premium')),
                ('employee_share', models.DecimalField(decimal_places=2, help_text="Employee's share (50%)", max_digits=10, verbose_name='Employee Share')),
                ('employer_share', models.DecimalField(decimal_places=2, help_text="Employer's share (50%)", max_digits=10, verbose_name='Employer Share')),
                ('effective_date', models.DateField(verbose_name='Effective Date')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'PhilHealth Contribution Table',
                'verbose_name_plural': 'PhilHealth Contribution Tables',
                'ordering': ['min_salary'],
            },
        ),
        migrations.CreateModel(
            name='PhilippinesRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('region_code', models.CharField(help_text='e.g., NCR, Region I, CAR', max_length=10, unique=True, verbose_name='Region Code')),
                ('region_name', models.CharField(max_length=100, verbose_name='Region Name')),
                ('daily_minimum_wage', models.DecimalField(decimal_places=2, default=0, help_text='Current daily minimum wage for this region', max_digits=10, verbose_name='Daily Minimum Wage')),
                ('monthly_minimum_wage', models.DecimalField(decimal_places=2, default=0, help_text='Computed as daily wage × working days', max_digits=10, verbose_name='Monthly Minimum Wage')),
                ('effective_date', models.DateField(help_text='Date when this wage rate became effective', verbose_name='Effective Date')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Philippines Region',
                'verbose_name_plural': 'Philippines Regions',
                'ordering': ['region_code'],
            },
        ),
        migrations.CreateModel(
            name='PhilippinesSSSContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Minimum Salary Range')),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maximum Salary Range')),
                ('monthly_salary_credit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monthly Salary Credit (MSC)')),
                ('employee_contribution', models.DecimalField(decimal_places=2, help_text="Employee's share (typically 4.5%)", max_digits=10, verbose_name='Employee Contribution')),
                ('employer_contribution', models.DecimalField(decimal_places=2, help_text="Employer's share (typically 9.5%)", max_digits=10, verbose_name='Employer Contribution')),
                ('total_contribution', models.DecimalField(decimal_places=2, help_text='Total SSS contribution (14%)', max_digits=10, verbose_name='Total Contribution')),
                ('ec_contribution', models.DecimalField(decimal_places=2, default=10.0, help_text="Employer's Compensation contribution (typically ₱10)", max_digits=10, verbose_name="EC (Employer's Compensation)")),
                ('effective_date', models.DateField(verbose_name='Effective Date')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'SSS Contribution Table',
                'verbose_name_plural': 'SSS Contribution Tables',
                'ordering': ['min_salary'],
            },
        ),
        migrations.CreateModel(
            name='PhilippinesTaxBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('min_annual_income', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Minimum Annual Income')),
                ('max_annual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Maximum Annual Income')),
                ('base_tax', models.DecimalField(decimal_places=2, default=0, help_text='Fixed tax amount for this bracket', max_digits=12, verbose_name='Base Tax')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='Tax rate for excess over minimum', max_digits=5, verbose_name='Tax Rate (%)')),
                ('effective_date', models.DateField(verbose_name='Effective Date')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Philippines Tax Bracket (TRAIN Law)',
                'verbose_name_plural': 'Philippines Tax Brackets (TRAIN Law)',
                'ordering': ['min_annual_income'],
            },
        ),
        migrations.CreateModel(
            name='PhilippinesThirteenthMonthPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('tax_exempt_amount', models.DecimalField(decimal_places=2, default=90000.0, help_text='Maximum tax-exempt 13th month pay (currently ₱90,000)', max_digits=12, verbose_name='Tax Exempt Amount')),
                ('computation_method', models.CharField(choices=[('total_basic', 'Total Basic Salary / 12'), ('prorated', 'Prorated Based on Months Worked')], default='total_basic', max_length=20, verbose_name='Computation Method')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': '13th Month Pay Configuration',
                'verbose_name_plural': '13th Month Pay Configurations',
                'unique_together': {('year', 'company_id')},
            },
        ),
        migrations.RemoveField(
            model_name='pagibigcontributiontable',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='pagibigcontributiontable',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='pagibigcontributiontable',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='payrollcountrysettings',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='payrollcountrysettings',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='payrollcountrysettings',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='philhealthcontributiontable',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='philhealthcontributiontable',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='philhealthcontributiontable',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='philippineemployeetaxinfo',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='philippineemployeetaxinfo',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='philippineemployeetaxinfo',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='philippineloan',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='philippineloan',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='philippineloan',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='philippinetaxbracket',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='philippinetaxbracket',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='philippinetaxbracket',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='ssscontributiontable',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='ssscontributiontable',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ssscontributiontable',
            name='modified_by',
        ),
        migrations.AlterUniqueTogether(
            name='thirteenthmonthpayconfig',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='thirteenthmonthpayconfig',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='thirteenthmonthpayconfig',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='thirteenthmonthpayconfig',
            name='modified_by',
        ),
        migrations.DeleteModel(
            name='DeMinimisCustomBenefit',
        ),
        migrations.DeleteModel(
            name='PagIBIGContributionTable',
        ),
        migrations.DeleteModel(
            name='PayrollCountrySettings',
        ),
        migrations.DeleteModel(
            name='PhilHealthContributionTable',
        ),
        migrations.DeleteModel(
            name='PhilippineEmployeeTaxInfo',
        ),
        migrations.DeleteModel(
            name='PhilippineLoan',
        ),
        migrations.DeleteModel(
            name='PhilippineTaxBracket',
        ),
        migrations.DeleteModel(
            name='SSSContributionTable',
        ),
        migrations.DeleteModel(
            name='ThirteenthMonthPayConfig',
        ),
        migrations.AddField(
            model_name='philippinescola',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.philippinesregion', verbose_name='Region'),
        ),
    ]
