# Generated by Django 4.2.21 on 2025-10-24 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0002_alter_reimbursement_description_ssscontributiontable_and_more'),
    ]

    operations = [
        # NOTE: All Philippine models already created in migration 0001_initial.py
        # This migration only cleans up temporary models from migration 0002
        # and adds the 'region' field to philippinescola
        
        migrations.RemoveField(
            model_name='pagibigcontributiontable',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='pagibigcontributiontable',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='pagibigcontributiontable',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='payrollcountrysettings',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='payrollcountrysettings',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='payrollcountrysettings',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='philhealthcontributiontable',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='philhealthcontributiontable',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='philhealthcontributiontable',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='philippineemployeetaxinfo',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='philippineemployeetaxinfo',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='philippineemployeetaxinfo',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='philippineloan',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='philippineloan',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='philippineloan',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='philippinetaxbracket',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='philippinetaxbracket',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='philippinetaxbracket',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='ssscontributiontable',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='ssscontributiontable',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ssscontributiontable',
            name='modified_by',
        ),
        migrations.AlterUniqueTogether(
            name='thirteenthmonthpayconfig',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='thirteenthmonthpayconfig',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='thirteenthmonthpayconfig',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='thirteenthmonthpayconfig',
            name='modified_by',
        ),
        migrations.DeleteModel(
            name='DeMinimisCustomBenefit',
        ),
        migrations.DeleteModel(
            name='PagIBIGContributionTable',
        ),
        migrations.DeleteModel(
            name='PayrollCountrySettings',
        ),
        migrations.DeleteModel(
            name='PhilHealthContributionTable',
        ),
        migrations.DeleteModel(
            name='PhilippineEmployeeTaxInfo',
        ),
        migrations.DeleteModel(
            name='PhilippineLoan',
        ),
        migrations.DeleteModel(
            name='PhilippineTaxBracket',
        ),
        migrations.DeleteModel(
            name='SSSContributionTable',
        ),
        migrations.DeleteModel(
            name='ThirteenthMonthPayConfig',
        ),
        migrations.AddField(
            model_name='philippinescola',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.philippinesregion', verbose_name='Region'),
        ),
    ]
