# Generated by Django 4.2.21 on 2025-11-09 06:39

from decimal import Decimal
from django.db import migrations


def fix_overtime_multipliers(apps, schema_editor):
    """
    Fix incorrect overtime multipliers for Philippines Labor Code compliance
    
    CORRECTIONS:
    1. regular_holiday_ot: 1.60 → 2.60 (260%)
       - Regular holiday = 200% base
       - With OT = 200% + (200% × 30%) = 260%
    
    2. regular_holiday_rest_day_ot: 2.60 → 3.38 (338%)
       - Regular holiday + rest day = 260%
       - With OT = 260% + (260% × 30%) = 338%
    
    Reference: Labor Code of the Philippines, Articles 93-94
    """
    PhilippinesOvertimeRule = apps.get_model('payroll', 'PhilippinesOvertimeRule')
    
    # Fix regular holiday OT (200% + 30% OT premium = 260%)
    regular_holiday_ot = PhilippinesOvertimeRule.objects.filter(
        overtime_type='regular_holiday_ot'
    ).first()
    
    if regular_holiday_ot:
        regular_holiday_ot.multiplier = Decimal('2.60')
        regular_holiday_ot.description = 'Regular holiday overtime - 260% of hourly rate (200% holiday + 30% OT)'
        regular_holiday_ot.save()
    
    # Fix regular holiday + rest day OT (260% base + 30% OT premium = 338%)
    regular_holiday_rest_ot = PhilippinesOvertimeRule.objects.filter(
        overtime_type='regular_holiday_rest_day_ot'
    ).first()
    
    if regular_holiday_rest_ot:
        regular_holiday_rest_ot.multiplier = Decimal('3.38')
        regular_holiday_rest_ot.description = 'Regular holiday + rest day overtime - 338% of hourly rate (260% base + 30% OT)'
        regular_holiday_rest_ot.save()


def reverse_overtime_multipliers(apps, schema_editor):
    """Reverse the overtime multiplier fixes"""
    PhilippinesOvertimeRule = apps.get_model('payroll', 'PhilippinesOvertimeRule')
    
    # Revert regular holiday OT
    regular_holiday_ot = PhilippinesOvertimeRule.objects.filter(
        overtime_type='regular_holiday_ot'
    ).first()
    
    if regular_holiday_ot:
        regular_holiday_ot.multiplier = Decimal('1.60')
        regular_holiday_ot.description = 'Regular holiday overtime - 160% of hourly rate'
        regular_holiday_ot.save()
    
    # Revert regular holiday + rest day OT
    regular_holiday_rest_ot = PhilippinesOvertimeRule.objects.filter(
        overtime_type='regular_holiday_rest_day_ot'
    ).first()
    
    if regular_holiday_rest_ot:
        regular_holiday_rest_ot.multiplier = Decimal('2.60')
        regular_holiday_rest_ot.description = 'Regular holiday + rest day overtime - 260% of hourly rate'
        regular_holiday_rest_ot.save()


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_payrollcountryconfig_constraints_and_audit'),
    ]

    operations = [
        migrations.RunPython(fix_overtime_multipliers, reverse_overtime_multipliers),
    ]

