# Generated by Django 4.2.21 on 2025-11-09 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0003_remove_employee_employee_ph_region_idx'),
        ('payroll', '0006_fix_overtime_multipliers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deduction',
            name='country',
            field=models.CharField(choices=[('USA', 'United States'), ('PH', 'Philippines'), ('GLOBAL', 'All Countries')], default='GLOBAL', help_text="Country where this deduction applies. Select 'All Countries' for universal deductions.", max_length=10),
        ),
        migrations.CreateModel(
            name='PhilippinesBIRForm2316',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('year', models.IntegerField(help_text='Calendar year for which this form is issued', verbose_name='Tax Year')),
                ('employer_tin', models.CharField(help_text='Tax Identification Number of employer', max_length=20, verbose_name='Employer TIN')),
                ('employer_name', models.CharField(max_length=255, verbose_name='Employer Name')),
                ('employer_address', models.TextField(verbose_name='Employer Address')),
                ('employee_tin', models.CharField(max_length=20, verbose_name='Employee TIN')),
                ('employee_name', models.CharField(max_length=255, verbose_name='Employee Name')),
                ('employee_address', models.TextField(verbose_name='Employee Address')),
                ('gross_compensation', models.DecimalField(decimal_places=2, default=0, help_text='Total compensation before deductions', max_digits=12, verbose_name='Gross Compensation Income')),
                ('non_taxable_13th_month', models.DecimalField(decimal_places=2, default=0, help_text='Up to ₱90,000 exempt', max_digits=12, verbose_name='Non-Taxable 13th Month & Other Benefits')),
                ('non_taxable_de_minimis', models.DecimalField(decimal_places=2, default=0, help_text='Rice, clothing, medical, laundry allowances', max_digits=12, verbose_name='Non-Taxable De Minimis Benefits')),
                ('non_taxable_sss', models.DecimalField(decimal_places=2, default=0, help_text='Employee share of mandatory contributions', max_digits=12, verbose_name='SSS/GSIS/PHIC/HDMF Contributions')),
                ('non_taxable_salaries', models.DecimalField(decimal_places=2, default=0, help_text='Other non-taxable compensation', max_digits=12, verbose_name='Salaries & Other Forms of Compensation (Non-Taxable)')),
                ('taxable_basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Taxable Basic Salary')),
                ('taxable_13th_month', models.DecimalField(decimal_places=2, default=0, help_text='Amount exceeding ₱90,000', max_digits=12, verbose_name='Taxable 13th Month & Other Benefits')),
                ('taxable_other_benefits', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Taxable Other Benefits')),
                ('personal_exemption', models.DecimalField(decimal_places=2, default=50000, help_text='₱50,000 standard personal exemption', max_digits=12, verbose_name='Personal Exemption')),
                ('additional_exemption', models.DecimalField(decimal_places=2, default=0, help_text='₱25,000 per dependent (max 4)', max_digits=12, verbose_name='Additional Exemption')),
                ('premium_paid', models.DecimalField(decimal_places=2, default=0, help_text='Max ₱2,400 or 2.4% of MWE, whichever is lower', max_digits=12, verbose_name='Premium Paid on Health Insurance')),
                ('tax_withheld_jan_to_nov', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tax Withheld January to November')),
                ('tax_withheld_december', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tax Withheld December')),
                ('tax_withheld_total', models.DecimalField(decimal_places=2, default=0, help_text='Sum of January-December withholding tax', max_digits=12, verbose_name='Total Tax Withheld')),
                ('generated_date', models.DateTimeField(auto_now_add=True, verbose_name='Generated Date')),
                ('is_substituted', models.BooleanField(default=False, help_text='Whether this is a substituted/corrected form', verbose_name='Is Substituted Filing')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bir_form_2316', to='employee.employee', verbose_name='Employee')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_bir_forms', to='employee.employee', verbose_name='Generated By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'BIR Form 2316',
                'verbose_name_plural': 'BIR Forms 2316',
                'ordering': ['-year', 'employee'],
                'indexes': [models.Index(fields=['employee', 'year'], name='bir_2316_emp_year_idx'), models.Index(fields=['year'], name='bir_2316_year_idx')],
                'unique_together': {('employee', 'year', 'is_substituted')},
            },
        ),
    ]
