# Generated by Django 4.2.21 on 2025-11-09 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0003_remove_employee_employee_ph_region_idx'),
        ('base', '0002_initial'),
        ('payroll', '0007_alter_deduction_country_philippinesbirform2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhilippinesDeMinimisBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('benefit_type', models.CharField(choices=[('rice', 'Rice Subsidy (₱2,000/month max)'), ('clothing', 'Uniform/Clothing Allowance (₱6,000/year max)'), ('medical', 'Medical Cash Allowance (₱1,500/month max)'), ('laundry', 'Laundry Allowance (₱300/month max)'), ('vacation_leave', 'Monetized Unused Vacation Leave (₱10,000/year max)'), ('achievement', 'Achievement Awards (₱10,000/year max)'), ('gift', 'Gifts - Christmas/Anniversary (₱5,000/year max)'), ('other', 'Other De Minimis Benefits')], max_length=20, verbose_name='Benefit Type')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount of benefit given', max_digits=10, verbose_name='Amount')),
                ('date_given', models.DateField(help_text='Date when benefit was provided', verbose_name='Date Given')),
                ('description', models.CharField(blank=True, help_text='Additional details about the benefit', max_length=255, verbose_name='Description')),
                ('is_within_limit', models.BooleanField(default=True, help_text='Whether this benefit is within the tax-free limit', verbose_name='Within Tax-Free Limit')),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount exceeding the tax-free limit (if any)', max_digits=10, verbose_name='Taxable Amount')),
                ('year', models.IntegerField(help_text='Year for tracking annual limits', verbose_name='Year')),
                ('month', models.IntegerField(help_text='Month (1-12) for tracking monthly limits', verbose_name='Month')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='de_minimis_benefits', to='employee.employee', verbose_name='Employee')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'De Minimis Benefit',
                'verbose_name_plural': 'De Minimis Benefits',
                'ordering': ['-date_given'],
                'indexes': [models.Index(fields=['employee', 'year'], name='deminimis_emp_year_idx'), models.Index(fields=['year', 'benefit_type'], name='deminimis_year_type_idx')],
            },
        ),
    ]
