# Generated by Django 4.2.21 on 2025-11-09 07:07

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0003_remove_employee_employee_ph_region_idx'),
        ('payroll', '0008_philippinesdeminimisbenefit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhilippinesFinalPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('separation_date', models.DateField(help_text='Last working day', verbose_name='Separation Date')),
                ('last_payroll_date', models.DateField(help_text='End date of last payroll processed', verbose_name='Last Payroll Date')),
                ('separation_reason', models.CharField(choices=[('resignation', 'Resignation'), ('retirement', 'Retirement'), ('end_of_contract', 'End of Contract'), ('termination', 'Termination (Just Cause)'), ('retrenchment', 'Retrenchment'), ('redundancy', 'Redundancy'), ('illness', 'Disease/Illness (Not Job-Related)'), ('closure', 'Business Closure'), ('other', 'Other')], max_length=20, verbose_name='Separation Reason')),
                ('unpaid_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Days worked after last payroll', max_digits=5, verbose_name='Unpaid Work Days')),
                ('daily_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Daily Rate')),
                ('unpaid_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Unpaid Salary')),
                ('total_basic_ytd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total basic salary earned from Jan 1 to separation', max_digits=12, verbose_name='Total Basic Salary YTD')),
                ('prorated_13th_month', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Pro-Rated 13th Month Pay')),
                ('months_worked', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Months worked in current year', max_digits=4, verbose_name='Months Worked')),
                ('unused_vacation_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Unused Vacation Leave Days')),
                ('unused_sick_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Unused Sick Leave Days')),
                ('leave_conversion_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Leave Conversion Amount')),
                ('is_entitled_to_separation_pay', models.BooleanField(default=False, help_text='Only for retrenchment, redundancy, closure, illness', verbose_name='Entitled to Separation Pay')),
                ('years_of_service', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Years of Service')),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Monthly Salary')),
                ('separation_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Varies by reason: 1 month/year or 0.5 month/year', max_digits=10, verbose_name='Separation Pay')),
                ('unpaid_loans', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Unpaid Loans/Advances')),
                ('other_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Damages, unreturned equipment, etc.', max_digits=10, verbose_name='Other Deductions')),
                ('ytd_tax_withheld', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='YTD Tax Withheld')),
                ('final_tax_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Recalculated tax based on total YTD income', max_digits=10, verbose_name='Final Tax Due')),
                ('tax_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Positive = refund, Negative = additional tax', max_digits=10, verbose_name='Tax Adjustment')),
                ('gross_final_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Gross Final Pay')),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Deductions')),
                ('net_final_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Net Final Pay')),
                ('calculation_date', models.DateTimeField(auto_now_add=True, verbose_name='Calculation Date')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Payment Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('calculated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_pays_calculated', to='employee.employee', verbose_name='Calculated By')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_pay_records', to='employee.employee', verbose_name='Employee')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Philippines Final Pay',
                'verbose_name_plural': 'Philippines Final Pay Records',
                'ordering': ['-separation_date'],
                'unique_together': {('employee', 'separation_date')},
            },
        ),
    ]
