# Generated by Django 4.2.21 on 2025-11-09 07:16

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_employee_employee_ph_region_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0009_philippinesfinalpay'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhilippinesGovernmentRemittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('form_type', models.CharField(choices=[('sss_r3', 'SSS Form R3 (Collection List)'), ('philhealth_rf1', 'PhilHealth Form RF-1'), ('pagibig_mcrf', 'Pag-IBIG MCRF')], max_length=20, verbose_name='Form Type')),
                ('period_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='monthly', max_length=10, verbose_name='Period Type')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('month', models.IntegerField(help_text='1-12 for monthly, 1/4/7/10 for quarterly', verbose_name='Month')),
                ('employer_name', models.CharField(max_length=200, verbose_name='Employer Name')),
                ('employer_id', models.CharField(help_text='SSS Number, PhilHealth Number, or Pag-IBIG Number', max_length=50, verbose_name='Employer ID/Number')),
                ('employer_address', models.TextField(verbose_name='Employer Address')),
                ('total_employees', models.IntegerField(default=0, verbose_name='Total Employees')),
                ('total_employee_contribution', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Employee Contribution')),
                ('total_employer_contribution', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Employer Contribution')),
                ('total_ec_contribution', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='SSS only', max_digits=12, verbose_name='Total EC (Employees Compensation)')),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Grand Total')),
                ('generated_date', models.DateTimeField(auto_now_add=True, verbose_name='Generated Date')),
                ('is_submitted', models.BooleanField(default=False, verbose_name='Submitted to Agency')),
                ('submission_date', models.DateField(blank=True, null=True, verbose_name='Submission Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='government_forms_generated', to='employee.employee', verbose_name='Generated By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Philippines Government Remittance',
                'verbose_name_plural': 'Philippines Government Remittances',
                'ordering': ['-year', '-month'],
                'unique_together': {('form_type', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PhilippinesGovernmentRemittanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('employee_id_number', models.CharField(help_text='SSS Number, PhilHealth Number, or Pag-IBIG Number', max_length=50, verbose_name='Employee ID Number')),
                ('employee_full_name', models.CharField(max_length=200, verbose_name='Employee Full Name')),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Monthly Salary Credit')),
                ('employee_contribution', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Employee Contribution')),
                ('employer_contribution', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Employer Contribution')),
                ('ec_contribution', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='SSS Employees Compensation - always ₱10', max_digits=10, verbose_name='EC Contribution')),
                ('total_contribution', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Contribution')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Employee')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('remittance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_entries', to='payroll.philippinesgovernmentremittance', verbose_name='Remittance Form')),
            ],
            options={
                'verbose_name': 'Government Remittance Entry',
                'verbose_name_plural': 'Government Remittance Entries',
                'ordering': ['employee_full_name'],
                'unique_together': {('remittance', 'employee')},
            },
        ),
    ]
