# Generated by Django 4.2.21 on 2025-12-18 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_add_is_new_employee_to_user'),
        ('employee', '0003_remove_employee_employee_ph_region_idx'),
        ('payroll', '0010_philippinesgovernmentremittance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('name', models.CharField(help_text='e.g., Payroll, Statutory, Bank Files, etc.', max_length=100, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text='CSS icon class for display', max_length=50, null=True, verbose_name='Icon Class')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Report Category',
                'verbose_name_plural': 'Report Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Report Name')),
                ('report_type', models.CharField(choices=[('payroll_register', 'Payroll Register'), ('variance_report', 'Variance Report'), ('employer_contributions', 'Employer Contributions'), ('bank_advice_list', 'Bank Advice List'), ('bank_file', 'Bank File'), ('sss_report', 'SSS Report'), ('philhealth_report', 'PhilHealth Report'), ('pagibig_report', 'PAG-IBIG Report'), ('bir_report', 'BIR Report'), ('bir_alphalist', 'BIR Alphalist'), ('bir_1601c', 'BIR 1601C'), ('bir_2316', 'BIR 2316'), ('net_pay_validation', 'Net Pay Validation'), ('basic_salary_report', 'Basic Salary Report'), ('recurring_adjustment_income', 'Recurring Adjustment Income'), ('recurring_adjustment_deduction', 'Recurring Adjustment Deduction'), ('withholding_tax_validation', 'Withholding Tax Validation'), ('certificate_contribution', 'Certificate of Contribution'), ('certificate_loan', 'Certificate of Loan'), ('statutory_report', 'Statutory Report'), ('demographic_report', 'Demographic Report'), ('leave_credits_report', 'Leave Credits Report'), ('attendance_summary', 'Attendance Summary'), ('overtime_report', 'Overtime Report'), ('13th_month_pay', '13th Month Pay Report'), ('year_end_report', 'Year End Report'), ('cost_center_analysis', 'Cost Center Analysis'), ('headcount_report', 'Headcount Report'), ('turnover_report', 'Turnover Report'), ('custom', 'Custom Report')], max_length=50, verbose_name='Report Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('output_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('dat', 'DAT File'), ('txt', 'Text File'), ('json', 'JSON')], default='pdf', max_length=20, verbose_name='Output Format')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('requires_date_range', models.BooleanField(default=True, verbose_name='Requires Date Range')),
                ('requires_company', models.BooleanField(default=False, verbose_name='Requires Company Selection')),
                ('requires_department', models.BooleanField(default=False, verbose_name='Requires Department Selection')),
                ('requires_employee', models.BooleanField(default=False, verbose_name='Requires Employee Selection')),
                ('columns_config', models.JSONField(blank=True, default=dict, help_text='JSON configuration for report columns', verbose_name='Columns Configuration')),
                ('filters_config', models.JSONField(blank=True, default=dict, help_text='JSON configuration for report filters', verbose_name='Filters Configuration')),
                ('sorting_config', models.JSONField(blank=True, default=dict, help_text='JSON configuration for default sorting', verbose_name='Sorting Configuration')),
                ('template_path', models.CharField(blank=True, help_text='Path to custom template file', max_length=255, null=True, verbose_name='Custom Template Path')),
                ('accessible_by_all', models.BooleanField(default=False, verbose_name='Accessible by All Users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accessible_departments', models.ManyToManyField(blank=True, related_name='accessible_reports', to='base.department', verbose_name='Accessible Departments')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='payroll.reportcategory', verbose_name='Category')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Report Template',
                'verbose_name_plural': 'Report Templates',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Schedule Name')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20, verbose_name='Frequency')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('next_run_date', models.DateTimeField(verbose_name='Next Run Date')),
                ('last_run_date', models.DateTimeField(blank=True, null=True, verbose_name='Last Run Date')),
                ('email_recipients', models.TextField(help_text='Comma-separated email addresses', verbose_name='Email Recipients')),
                ('email_subject', models.CharField(max_length=255, verbose_name='Email Subject')),
                ('email_body', models.TextField(blank=True, verbose_name='Email Body')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.department', verbose_name='Department')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('report_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='payroll.reporttemplate', verbose_name='Report Template')),
            ],
            options={
                'verbose_name': 'Report Schedule',
                'verbose_name_plural': 'Report Schedules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='payroll_reports/%Y/%m/%d/', verbose_name='Report File')),
                ('file_name', models.CharField(max_length=255, verbose_name='File Name')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Date From')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Date To')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Generation Parameters')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('processing_time', models.DurationField(blank=True, null=True, verbose_name='Processing Time')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.department', verbose_name='Department')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_about', to='employee.employee', verbose_name='Employee')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='employee.employee', verbose_name='Generated By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('report_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='payroll.reporttemplate', verbose_name='Report Template')),
            ],
            options={
                'verbose_name': 'Generated Report',
                'verbose_name_plural': 'Generated Reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='BankFileConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('name', models.CharField(max_length=200, verbose_name='Configuration Name')),
                ('bank', models.CharField(choices=[('bdo', 'BDO'), ('bpi', 'BPI'), ('metrobank', 'Metrobank'), ('security_bank', 'Security Bank'), ('unionbank', 'UnionBank'), ('landbank', 'Landbank'), ('pnb', 'PNB'), ('rcbc', 'RCBC'), ('eastwest', 'EastWest Bank'), ('chinabank', 'China Bank'), ('generic', 'Generic Format')], max_length=50, verbose_name='Bank')),
                ('file_format', models.CharField(choices=[('csv', 'CSV'), ('txt', 'Text File'), ('dat', 'DAT File'), ('excel', 'Excel')], default='csv', max_length=20, verbose_name='File Format')),
                ('delimiter', models.CharField(default=',', help_text='Field delimiter for text files', max_length=10, verbose_name='Delimiter')),
                ('include_header', models.BooleanField(default=True, verbose_name='Include Header Row')),
                ('date_format', models.CharField(default='%Y-%m-%d', help_text='Python strftime format', max_length=50, verbose_name='Date Format')),
                ('field_mapping', models.JSONField(default=dict, help_text='Maps internal fields to bank file columns', verbose_name='Field Mapping')),
                ('file_name_template', models.CharField(default='payroll_{date}.csv', help_text='Use {date}, {company}, etc. as placeholders', max_length=255, verbose_name='File Name Template')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_configs', to='base.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Bank File Configuration',
                'verbose_name_plural': 'Bank File Configurations',
                'ordering': ['bank', 'name'],
            },
        ),
    ]
