# Generated by assistant on 2025-12-23
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_reportcategory_reporttemplate_reportschedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='philippinesregion',
            name='region_code',
            field=models.CharField(help_text='e.g., NCR, Region I, CAR', max_length=20, unique=True, verbose_name='Region Code'),
        ),
    ]
